# Generated by Django 3.2.11 on 2022-03-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='state_id',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='color_id',
            new_name='state_id',
        ),
    ]
